baseURL = 'https://swrnv-qc.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'terminal'

[params.logo]
  logoText = "Swrnv-qc"
  logoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "https://swrnv-qc.github.io/resume/"
    weight = 1
