baseURL = 'https://swrnv-qc.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'terminal'

[params.logo]
  logoText = "Swrnv-qc"
  logoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/"
    weight = 1
